### ISSUE TITLE
[Request] Solid border around focused card as alternative to glow 

### ISSUE THREAD

**Issue by damomato** [spocky/miproja1#362]
Fantastic launcher thanks for your hard work. I would like to request a solid black border (or customisable colour) for the focus card.

At the moment I'm using the projectivity icons pack with background opacity set to 0, so you only see the icon. The only way to see a border around the focused card is to use the glow card effect. It works well but a solid thing border would look nicer for this set up.

**Comment by ZeroFoxx** [comment]
I'd like this too, but in addition, allowing for the glows gradient effect to be applied to the border. 

Right now the only way to get that effect is have transparent icons that are non rounded (don't know if that's a bug), or as mentioned have 0 opacity.

**Comment by spocky** [comment]
Fixed in 4.70

**Comment by damomato** [comment]
Parden my ignorance if I'm not finding this option, but I still don't think I can do this?

The new update allows a new border colour on focused cards, which is great as I've made this the accent colour and it looks really nice.

However, I still can't make it a solid border, I can still only use glow. And I still can't make it rounded.
