### ISSUE TITLE
Youtube Channel not Visible.

### ISSUE THREAD

**Issue by zimbow555** [spocky/miproja1#64]
Hi, previously Youtube App, had its own dedicated 'channel row' with the ability for me to select (1/or 3)...now this has gone. I have gone to Settings>Channels>and looked through available 'apps' and for some reason YT is not visible. I do have a YT alternative 'Smarttube' which does work thou. {I have deleted the YT app, and reinstalled. No change] I am also running latest build 4.5.1

**Comment by spocky** [comment]
Nothing should be changed in this regard. Could you please confirm that if you're using 4.36, the youtube channel is visible again ?
From my experience, youtube alternative apps (I don't remember if it is SmartTube, Smart Youtube Tv or another one) might interfere with Youtube channels because some of them use the same  Channel internal IDs as Youtube so depending on the order in Android's database, you get one or another but not both. I can confirm Projectivy was consistent with how the Stock Launcher behaved when I noticed this.

**Comment by Fabrice19730526** [comment]
That's an androidtv issue.

This should fix the issue.
Play Store Settings - Don't Auto Update Apps

Play Store - Uninstall Youtube (updates)

Settings - Apps - Youtube - Clear Data

Settings - Apps - Android TV Home - Uninstall updates & Clear Data

Reboot

Choose profile for Android TV & Youtube

Customize your home screen - Youtube Channels should be back

**Comment by zimbow555** [comment]
Unfortunately, that didnt solve my problem. I deleted SmartTube, Cleaned the Cache, Disabled Auto-Update Apps, Signed out & Cleared YT cache, deleted YT & YTMusic, rebooted. Reinstalled - <Customize home screen> still doesnt show YT as a channel.

**Comment by spocky** [comment]
Could you please check if it's currently working fine on the stock launcher ? If not, there's nothing I can do and this is due to an Android and/or Youtube update. Projectivy isn't doing anything fancy with the channels (it has no right to delete them or any of their program), it just displays what is returned by the OS.
If on your current configuration, you can see the Youtube Channel on the stock launcher, then this is probably a bug that could potentially be fix on Projectivy.

**Comment by Fabrice19730526** [comment]
Clear Cache and uninstall updates of Youtube and AndroidTV Home did the trick on Shield, Chromecast and Homatics Box R 4K. 

Block play store auto updates or the issue will reappear.

**Uninstalling/Reinstalling the apps will not sort this issue.**

**Comment by spocky** [comment]
Closing this as this behavior is not dependent on Projectivy but YouTube version.
